name: Execute Terraform Apply to GCP
on:
  workflow_call:
    inputs:
      project_id:
        required: true
        type: string
      workspace:
        required: true
        type: string    
    secrets:
      GCP_CREDENTIALS:
        required: true    
jobs:
  exec-terraform-apply:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure GCP credentials
        run: |
          mkdir -p terraform
          echo '${{ secrets.GCP_CREDENTIALS }}' > ${{ github.workspace }}/gcp-key.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=${{ github.workspace }}/gcp-key.json" >> $GITHUB_ENV
          gcloud auth activate-service-account --key-file=${{ github.workspace }}/gcp-key.json  
          gcloud config set project ${{ inputs.project_id }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Workspace Select
        run: terraform workspace select ${{ inputs.workspace }} 

      - name: Validate Terraform configuration
        run: terraform validate
        
      - name: Plan Terraform changes
        id: plan
        run: terraform plan -out='tfplan-${{ inputs.project_id }}-${{ github.run_id }}.out' > tfplan-${{ inputs.project_id }}-${{ github.run_id }}.out

      - name: Terraform Apply
        run: terraform apply -tfplan-${{ inputs.project_id }}-${{ github.run_id }}.out
